* My Emacs Configuration
  This configuration is meant to be used with Emacs 24. It is not guaranteed,
  or even likely, that it will work with anything less than that.

** Where's the Code?

   If you look at =init.el=, you will only see a short snippet of
   code. This code loads the org-mode file =start.org= and then
   executes the Emacs Lisp code in there. This is fantastic, because
   it allows me to document my configuration through org-mode instead
   of through comments.

   Strangely, I found that when I could organize my configuration with
   org-mode, I did not need to split it into a bunch of different
   files. My theory is that I was using the separate files to name
   sections of my configuration, which I can do just as well with the
   structure of org-mode.

   Unfortunately, org-mode files do not always render well on Github
   -- code blocks are not formatted at all. You can feel free to look
   at the code here, but I suggest pulling it down and looking at it
   within Emacs for now.

** Values and Goals
   My #1 value to impress on this config is simplicity. If I can get away
   with not including something, I will.

   My #1 goal when writing this config is to learn Emacs Lisp better. I know
   Scheme (particularly PLT Racket) pretty well, but I don't really know Emacs 
   Lisp.

