;;; Keybindings
(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "C-/") 'undo-tree-undo)
(global-set-key (kbd "C-?") 'undo-tree-redo)
(global-set-key (kbd "C-;") 'comment-or-uncomment-region)
(global-set-key (kbd "M-SPC") 'hippie-expand)
(global-set-key (kbd "M-/") 'hippie-expand)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)

(if window-system (global-unset-key (kbd "C-z")))

;;; user definitions
(global-set-key (kbd "C-c a") 'mark-whole-buffer)
(global-set-key (kbd "C-c C-a") 'my-anything)
(global-set-key (kbd "C-x C-a") 'my-anything)
(global-set-key (kbd "C-c c") 'query-replace-regexp)
(global-set-key (kbd "C-c d") 'deft)
(global-set-key (kbd "C-c f") 'find-file-in-project)
(global-set-key (kbd "C-c C-f") 'find-file-in-project)
(global-set-key (kbd "C-c g") 'magit-status)
(global-set-key (kbd "C-c C-g") 'find-file-in-git-repo)
(global-set-key (kbd "C-c m") 'clean-buffer)
(global-set-key (kbd "C-c q") 'join-line)
(global-set-key (kbd "C-c r") 'revert-buffer)
(global-set-key (kbd "C-c s") 'save-buffer-always)
(global-set-key (kbd "C-c C-s") 'save-buffer-always)
(global-set-key (kbd "C-c v") 'eval-buffer)
(global-set-key (kbd "C-c w") 'whitespace-mode)
(global-set-key (kbd "C-c x") 'execute-extended-command)
(global-set-key (kbd "C-c z") 'zap-to-char)

(windmove-default-keybindings 'meta)
